gui:
  sidePanelWidth: 0.2
  switchTabsWithPanelJumpKeys: true
  mainPanelSplitMode: horizontal
  useHunkModeInStagingView: false
git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers
